### ISSUE TITLE
flake8 finds no issues

### ISSUE THREAD

**Issue by romquentin** [AtomLinter/linter-flake8#283]
Hi, 

I experienced this error using atom and flake8 with OS El Capitan.

```
Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I reinstalled atom and flake8 and add the executable path (/Applications/anaconda/bin/flake8) in flake8 settings. Now I do not see any error but flake8 does not find any issue in my code (not working).

Thanks for your help!

Romain

**Comment by Arcanemagus** [comment]
Can you do the following:

1. Open up Developer Tools in Atom (View -> Developer -> Toggle Developer Tools)
2. Go to the Sources tab and open up the folder for this package
3. Open `main.js` 
4. Click on [line 240](https://github.com/AtomLinter/linter-flake8/blob/v2.1.1/lib/main.js#L240) to place a breakpoint there
5. Trigger a lint on a file you think has errors
6. Report back what `result` contains

Thanks!

**Comment by romquentin** [comment]
Hey, 
Just to be sure: 
I opened Developer Tools and opened ~.atom/packages/linter-flake8/lib/main.js
I placed a breakpoint on line 240 and trigger a lint on a file with errors. The debugger paused and I am not sure what is the `result`sestion?
Thanks

**Comment by romquentin** [comment]
Ok, I got that:
`result = Object {stdout: "", stderr: "Traceback (most recent call last):↵ File "/Applic…odestyle↵ImportError: No module named pycodestyle", exitCode: 1}, execPath = "/Applications/anaconda/bin/flake8", parameters = ["--format=default", "--max-complexity", -1, "-"], options = Object {stdin: "import matplotlib.pyplot as plt↵import os.path as …↵ print('cue_type', 'Cue')↵↵ report.save()↵", cwd: "/Users/quentinra/Desktop/MEGdata/romain_wm", stream: "both"}`

**Comment by Arcanemagus** [comment]
Looks like the `flake8` you are pointing to wasn't installed properly as it is missing `pycodestyle`. How did you install it? `pip install flake8` should have taken care of that for you.

**Comment by romquentin** [comment]
I installed it with the atom package installer. I will uninstall flake8 and try again with pip

**Comment by romquentin** [comment]
I uninstalled flake8 in atom settings and re-installed it with pip. Now it does not appear in the community packages in atom settings.
which flake8 in a terminal gives me /Applications/anaconda/bin/flake8
Thank you for your help

**Comment by romquentin** [comment]
Ok, after re-installing flake8 with pip, 
`result`contains
`result = Object {stdout: "", stderr: "Traceback (most recent call last):↵ File "/Applic…rocessor' object has no attribute 'physical_line'", exitCode: 1}, execPath = "/Applications/anaconda/bin/flake8", parameters = ["--format=default", "--max-complexity", -1, "-"], options = Object {stdin: "# coding: utf-8↵import os↵import os.path as op↵imp… client.upload(fname, overwrite=True)↵", cwd: "/Users/quentinra/Desktop/MEGdata/romain_wm", stream: "both"}`

**Comment by romquentin** [comment]
and running flake8 in the terminal gives me that error:
`"hacking.core" requested unknown parameters causing 'FileProcessor' object has no attribute 'physical_line'`
Thanks a lot!

**Comment by romquentin** [comment]
It has something to do with hacking module. It works well if I uninstall hacking...

**Comment by Arcanemagus** [comment]
`linter-flake8` (this Atom package) and `flake8` (the Python program) are two entirely different things 😛.

This package is simply running `flake8` and translating the output into a format that is understood by the Linter Atom package for displaying inside Atom, so if `flake8` isn't working in the CLI it won't be working here.

The `hacking` module is _extremely_ out of date btw, and forces very old versions of everything, I would recommend against it unless you absolutely need the few extra checks it provides.

**Comment by momit-rahman** [comment]
My problem is same that no issue can't find linter-flake8 after update Atom and flake8. I am using Linux Mint 18. Its can find issue when I change code format 'Python (Django)' to only ' Python'. I don't know what the magic behind it. I am just trying to discuss with the situation.

**Comment by romquentin** [comment]
Ok :) Thank you!

**Comment by Arcanemagus** [comment]
It sounds like your issue has been resolved, if that's not the case please elaborate on any further problems you are having and re-open this issue 😉.

**Comment by gitanupam** [comment]
@romquentin @Arcanemagus  I am facing exactly the same issue on OS El Captain. So flake8 doesnt work on this OS if installed directly from Atom (and not pip), is it? 

I am using Atom 1.14.1

**Comment by gitanupam** [comment]
Actually, I read the docs now and it seems I anyways needed to install flake8 along with linter-flake8 (sorry, I didnt realise that it was a pre-req and not the same thing). So I just did:

pip install flake8.

But I still get the following error:

Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by gitanupam** [comment]
FYI: Got it working by following the suggestion [here](https://github.com/AtomLinter/linter-ruby/issues/80#issuecomment-244625389)  (I'm not using Ruby though).

Ran `which flake8` and pasted the output in the field 'Executable Path' under the linter package's 'Settings' in Atom.
