### ISSUE TITLE
Python f-string E999-Syntar Error invalid syntax

### ISSUE THREAD

**Issue by DorMiX** [AtomLinter/linter-flake8#580]
Hello,
I have experienced this error message 
at this line:
`self.assertRedirects(response, f'/lists/{new_list.id}/')`
The ') signs are only underlined and flake says it is invalid syntax

**Comment by Arcanemagus** [comment]
What version of `flake8` are you using?

**Comment by JoshuaC3** [comment]
I too have found this issue. It seems that it is running in python 2 but I do not know how to change this...

**Comment by jeanmw** [comment]
Likewise.

**Comment by Trivikram1** [comment]
I had flake8 installed for both python2 and python3 and flake8 was being defaulted to python2, so I did the following

**Comment by Arcanemagus** [comment]
Since none of you have actually answered [the question](https://github.com/AtomLinter/linter-flake8/issues/580#issuecomment-383141455), I'm going to assume that you are all using an out of date version of `flake8` with a known bug affecting _all_ `9xx` error codes. Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

Closing this as there has been no response from @DorMiX about this.

**Comment by geniousisme** [comment]
I use flake8 3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.7.0 on Darwin, and the error still exist :(

**Comment by Arcanemagus** [comment]
@geniousisme Please head over to #626 and answer https://github.com/AtomLinter/linter-flake8/issues/626#issuecomment-411172768, thanks ;)

**Comment by matthew-nm** [comment]
The solution that worked for me is that from @Trivikram1. I essentially had to do
~~~
pip uninstall flake8
pip3 install flake8
~~~
even though my original flake8 installation was installed to my python3 virtual env using pip, it was the python2 version of flake8. You can tell the difference by looking at the CPython version number printed by the `flake8 --version` command. Before reinstalling, the CPython version printed was "2.7.15", but after reinstalling with `pip3`, the CPython version was "3.6.5".

**Comment by lipis** [comment]
I have the 3.8.2 and still get the invalid syntax for f-strings.
